FROM ubuntu:18.04

EXPOSE 80
ENV PORT 80
ENV CODE_VERSION 4.9.1
WORKDIR /code-server
COPY ./config.yaml ./
COPY ./code-server_${CODE_VERSION}_amd64.deb ./
RUN dpkg -i code-server_${CODE_VERSION}_amd64.deb

ENTRYPOINT ["code-server"]
CMD ["--config", "/code-server/config.yaml", "/app"]