name: Publish to Aliyun

on:
  push:
    branches: 
      - v*

env:
  IMAGE_NAME: code-server

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALIYUN_EMAIL }} --password-stdin

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Push image
        run: |
          IMAGE_ID="registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_USERNAME }}/$IMAGE_NAME"

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ steps.vars.outputs.short_ref }}" | sed -e 's/^aliyun-//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo "version: $VERSION"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION